sonar.projectKey=lepture_mistune
sonar.organization=lepture

sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.test.inclusions=tests/**/test_*.py

sonar.python.version=3.10, 3.11, 3.12, 3.13, 3.14
sonar.python.coverage.reportPaths=coverage.xml

sonar.githubactions.activate=false
